### PR TITLE
Do not permit the client to send empty messages

### PR DESCRIPTION
**Pull request by OmniTroid**

### CODE REVIEW

**Comment by in1tiate** [comment]
Is there a reason the client shouldn't be allowed to send empty messages?

**Comment by in1tiate** [comment]
Desktop client allows empty messages. It's on the server to detect and reduce spam, per convention - how bad of a problem is this?

**Comment by in1tiate** [comment]
I guess it doesn't hurt anything. Someone will probably complain, but that's not unusual

**Comment by stonedDiscord** [comment]
Sadly some roleplay mechanics rely on empty messages

**Pull request closed without merging**
