### PR TITLE
Adding support for multiple audio outputs

### PR DESCRIPTION
**Pull request by caleb-mabry**

### CODE REVIEW

**Comment by stonedDiscord** [comment]
image
oof

**Comment by caleb-mabry** [comment]
> image oof

This is sadly the expected behavior for this. If you deny it, then I'm not allowed to see what audio devices are connected to your computer.

**Comment by caleb-mabry** [comment]
ALSO NOTE! This is not a widely supported thing on web.

**Comment by stonedDiscord** [comment]
the alert popping up as soon as the page loads is unacceptable but i think it's fine if it pops up when you click the audio device dropdown and the dropdown says "please click allow" until you do so.

**Comment by caleb-mabry** [comment]
Once https://github.com/AttorneyOnline/webAO/pull/117 and https://github.com/AttorneyOnline/webAO/pull/119 are merged in, I'll work on the flow for this. 
I'll mock up some figma designs and show them to the devs so we can get a better understanding of the flow while I'm waiting

**Comment by oldmud0** [comment]
Please be sure to run this by product as well

**Comment by caleb-mabry** [comment]
Not worrying about this because it is only supported on HTTPS

**Pull request closed without merging**
