### PR TITLE
Separating all of Client.TS

### PR DESCRIPTION
**Pull request by caleb-mabry**
An attempt to make the client easier to read and more maintainable. 
I'm opening this PR as a draft to receive feedback through the development process because, as it currently stands, there are 93 file changes

### CODE REVIEW

**Comment by stonedDiscord** [comment]
i didn't know we even had 93 files

**Comment by dyviacat** [comment]
i didnt know we even had files

**Comment by stonedDiscord** [comment]
luckily we don't  have a stale PR bot or it would piss all over this

**Comment by stonedDiscord** [comment]
what happened to client.html why is there a big ass merge conflict

**Comment by caleb-mabry** [comment]
Life has gotten too busy and this PR should be done in smaller chunks

**Pull request closed without merging**
