### PR TITLE
Move INI parser

### PR DESCRIPTION
**Pull request by caleb-mabry**
Changed logic a little bit in the ini parser to hopefully make more sense to read it.

Also moved it into another file to slowly chip away at the `client.js` filesize.

### CODE REVIEW

**Comment by caleb-mabry** [comment]
Maybe I put this out of scope. But this adds unit testing as well.

**Comment by stonedDiscord** [comment]
can we put the tests inside a separate folder?

**Comment by caleb-mabry** [comment]
@stonedDiscord Latest commit solves this. Great call out!
webAO/__tests__/iniParse.test.js
They'll be stored under that. As we begin to test more and more, the base folder structure for each level will have its own `__tests__`

**Comment by stonedDiscord** [comment]
can we add a new CI run for the tests?

**Pull request merged**
