### PR TITLE
delete bbcode

### PR DESCRIPTION
**Pull request by stonedDiscord**
only supported by the webclient, while the desktop client has similiar features with a different implementation

### CODE REVIEW

**Comment by oldmud0** [comment]
thank you for removing qubrickao

**Comment by oldmud0** [comment]
oh crap what are we gonna do with shake/flash

**Comment by stonedDiscord** [comment]
isn't affected by bbcode

**Comment by oldmud0** [comment]
yeah but it's another nonstandard thing

**Pull request merged**
