### PR TITLE
Urgent cache busting

### PR DESCRIPTION
**Pull request by vintprox**
Users actually get trouble with refreshing stuff on their side, it should be made in here. We could automatize the change of versions, but maybe later.

## Manual Workaround
If you make drastic changes in `client` files, make sure to change version number(s) in `client.html` before deploying for production.

### CODE REVIEW

**Comment by oldmud0** [comment]
You can change the generator in webpack to emit chunk hashes as part of the filename.

**Comment by oldmud0** [comment]
This will do for now....

**Comment by stonedDiscord** [comment]
how do i reload page????????

**Comment by vintprox** [comment]
Is it sarcasm? Page itself (HTML) should not be cached. The issue is about reloading without script and stylesheet cache.

**Comment by stonedDiscord** [comment]
longbyte did you upload it
people are still complaining

**Comment by stonedDiscord** [comment]
ok he did and users are stupid

**Pull request merged**
